'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
'''

#Find nth fibonacci number
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        a, b = 0, 1
        for i in range(n-1):
            a, b = b, a+b
        return b

#Find the sum of even Fibonacci numbers below n
def fibonacci_below(n):
    f=0
    solution=0
    counter=0
    while f<n:
        f=fibonacci(counter)
        if f%2==0:
            solution+=f
        counter+=1
    return solution

print(fibonacci_below(4000000))
