'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
'''

#sum even fibonacci numbers below n
def sum_even_fib_below_n(n):
    sol=0

    #initial numbers
    a=1
    b=2

    #loop to get fib numbers
    while b<n:
        a, b = b, a+b
        if a%2==0:
            sol+=a
    return sol

#parameter
n=4000000

print(sum_even_fib_below_n(n))

